PTC_QA/PTC_QA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('daily_QA.urls')),
]

PTC_QA/daily_QA/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name='daily_QA'
#from daily_QA.views import daily_reload

urlpatterns = [
    path('home', views.home, name="home"),
    path('gtrselect', views.gtrselect, name="gtrselect"),
    path('daily<int:gtr>', views.daily, name="daily"), #path converter
    path('weekly', views.weekly, name="weekly"),
    path('monthly', views.monthly, name="monthly"),
    path('login', views.inlog, name="inlog"), 
    path('daily_reload', views.daily_reload, name='daily_reload'), #'daily_reload/<int:pk>'
    #path('validate', views.validovat, name='validovat'),
    #path('success2/<str:gtr>/', views.success2, name="success2"),
    path('success2', views.success2, name="success2"),
    path('submitted', views.submitted, name="submitted"),
    path('entries_by_gtr<int:gtr>', views.view_entries_by_gtr, name="entries_by_gtr"),
    path('entry_detail/<index>', views.entry_detail, name="entry_detail"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

PTC_QA/daily_QA/forms.py
#NOTE this form isn't necessary if we're making them by hand in html

from django import forms
from django.forms import ModelForm
from .models import DailyTest, DailyTestInput

#Create daily QA form
class DailyTestForm(ModelForm):
    # define the fields to render, inherit from daily.html?
    date_added = forms.DateTimeField(widget=forms.DateTimeInput(format='%Y-%m-%d %H:%M', attrs={'type': 'date'}),required=False)
    #gantry_choices=[(1, "FBTR1"),(2, "GTR2"),(3, "GTR3"),(4, "GTR4")]
    #gantry = forms.IntegerField(widget=forms.Select(choices=gantry_choices))gantry = forms.IntegerField(widget=forms.Select(choices=gantry_choices))
    gantry = forms.IntegerField(required=False)
    visionrt_check = forms.BooleanField(label="Vision RT?",required=False)
    flatpanels_check = forms.BooleanField(label="Flat panely?",required=False)
    dynr = forms.BooleanField(label="DynR?",required=False)
    lasers = forms.BooleanField(label="Lasery x, y, z?",required=False)
    temperature = forms.DecimalField(required=False)
    pressure = forms.DecimalField(required=False)
    kfactor = forms.DecimalField(required=False)

    class Meta:
        model = DailyTest
        #fields = ['date_added', 'visionrt_check', 'flatpanels_check', 'dynr', 'lasers']
        #exclude = ('gantry',)
        #fields = ('') #make a list of required fields
        fields = '__all__'
        

#Create daily QA form
class DailyTestInputForm(ModelForm):
    #index = forms.AutoField(db_column='Index', primary_key=True)  # Field name made lowercase.
    energyID = forms.IntegerField(required=False)
    input1 = forms.DecimalField(max_digits=10, decimal_places=4)  # Field name made lowercase.
    input2 = forms.DecimalField(max_digits=10, decimal_places=4, required=False)  # Field name made lowercase.
    input3 = forms.DecimalField(max_digits=10, decimal_places=4, required=False)  # Field name made lowercase.
    input4 = forms.DecimalField(max_digits=10, decimal_places=4, required=False)  # Field name made lowercase.
    configID = forms.IntegerField(required=False)
    #indexid = forms.ForeignKey(DailyTest, on_delete=forms.CASCADE, null=True) 

    class Meta:
        model = DailyTestInput
        #fields = '__all__'
        exclude = ('indexid',)

PTC_QA/daily_QA/views.py
from django.shortcuts import render, redirect
from .models import DailyTest, DailyTestInput, DLynxMeasurement, DailyTestDraft, DIcMeasurement, DMlicMeasurement #must import all needed tables
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.utils import timezone
from datetime import date
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import Q
from django.urls import reverse
import json



#@login_required   
def inlog(request):
    if request.method == "POST":
        loginform = AuthenticationForm(request, data=request.POST)
        if loginform.is_valid():
            user = loginform.get_user()
            #print(user)
            login(request, user)
            return redirect('daily_QA:home')
    else:
        loginform = AuthenticationForm(request)

    return render(request,'daily_QA/inlog.html',{
    'loginform':loginform})

def home(request):
    return render(request, 'daily_QA/home.html')


def gtrselect(request): 
    return render(request, 'daily_QA/gtrselect.html')

def ajax_get_view(request, form): # May include more arguments depending on URL parameters
    # Get data from the database - Ex. Model.object.get(...)
    #identify record's index
    listbygantry = DailyTestDraft.objects.values().filter(gantry=gtr)#.order_by("-index",)[0]
    last=listbygantry.order_by('-index')[0]
    index = (last['index'])
    form = DailyTestDraft.objects.get(pk=index)
    Temp_test = form.temperature
    print(Temp_test)
    data = {
            'my_data':Temp_test
    }
    return JsonResponse(data)

def daily(request,gtr):
    path_name = request.resolver_match.view_name
    datacheck = DailyTestDraft.objects.filter(gantry=gtr,date_added__contains=timezone.now().date())
    if datacheck.count()==0: 
        form = DailyTestDraft.objects.create(gantry=gtr, date_added = timezone.now()) 
          
    #identify record's index
    listbygantry = DailyTestDraft.objects.values().filter(gantry=gtr)#.order_by("-index",)[0]
    last=listbygantry.order_by('-index')[0]
    index = (last['index'])
    form = DailyTestDraft.objects.get(pk=index)
    
    if request.GET.get('reload', None):
        # Retrieve the data from the database and pass it to the template
        print('boa jeho')
        #reload_function()
        #username = request.GET.get('Temp_test', None)
        #print(temp_test)
        #print(request.GET.get(''))
        print(str(form.temperature))
        response1 = dict()
        response1.update({'temp_test': str(form.temperature)})
        print(response1)
        return JsonResponse({'temp_test': str(form.temperature)}) 
        #return HttpResponse(response1) 
    

    if request.method == "POST" and request.POST.get('tlacitko')!='Submit':   

        fields_mapping = {
            'temperature': 'Temp',
            'pressure': 'Pres',
            'kfactor': 'kfactor',
            'laserx': 'X',
            'lasery': 'Y',
            'laserz': 'Z',
            'flatpanels_check': 'FlatPanels',
            'visionrt_check': 'VisionRT',
            'dynr': 'DynR',
            'lynxid': 'LynxID',
            'lynx70_95': 'L7095',
            'lynx70_99': 'L7099',
            'lynx70_max': 'L70max',
            'lynx70_avg': 'L70avg',
            'lynx115_95': 'L11595',
            'lynx115_99': 'L11599',
            'lynx115_max': 'L115max',
            'lynx115_avg': 'L115avg',
            'lynx145_95': 'L14595',
            'lynx145_99': 'L14599',
            'lynx145_max': 'L145max',
            'lynx145_avg': 'L145avg',
            'lynx226_95': 'L22695',
            'lynx226_99': 'L22699',
            'lynx226_max': 'L226max',
            'lynx226_avg': 'L226avg',
            'icid': 'IcID',
            'ic70_mu': 'K70mu',
            'ic70_nc': 'K70nc',
            'ic100_mu': 'K100mu',
            'ic100_nc': 'K100nc',
            'ic170_mu': 'K170mu',
            'ic170_nc': 'K170nc',
            'ic226_mu': 'K226mu',
            'ic226_nc': 'K226nc',
            'mlicid': 'MlicID',
            'mlic70_range': 'MLIC70',
            'mlic100_range': 'MLIC100',
            'mlic170_range': 'MLIC170',
            'mlic226_range': 'MLIC226',
            # Add more fields here
        }

        # Iterate through the dictionary to update form fields
        for field_name, request_param in fields_mapping.items():
            param_value = request.POST.get(request_param)
            if param_value is not None:
                if param_value == 'true':
                    setattr(form, field_name, 1)
                elif param_value == 'false':
                    setattr(form, field_name, 0)
                else:
                    setattr(form, field_name, param_value)
            
        form.save()

    #if request.GET.get('reload'):
        #Temp_test = form.temperature
        #print(Temp_test)
        #data = {
        #        'my_data':Temp_test,
        #        'gtr': gtr
        #}
        #return JsonResponse(data)
        #return JsonResponse(data)
        #return render(request, 'daily_QA/'+str(gtr)+'.html', {'data': json.dumps(response)})
        

            #return render(request, 'daily_QA/' + str(gtr) + '.html', {'gtr': gtr, 'Temp_test': temp_test})
        #return render(request, 'daily_QA/' + str(gtr) + '.html', {'gtr': gtr})
 

    #if request.POST.get('reload') == 'Reload':
        
        

            #return render(request, 'daily_QA/' + str(gtr) + '.html', {'gtr': gtr, 'Temp_test': temp_test})
        #return render(request, 'daily_QA/' + str(gtr) + '.html', {'gtr': gtr})
    


    if request.POST.get('tlacitko')=='Submit':
        current_user = request.user  # Retrieve the currently logged-in user


        #if request.POST.get('checksAllChecks')=='1':
            #form.validate = 1
        
        #submit code here      
        submitted(form, current_user)
        return render(request, 'daily_QA/success2.html',{})
        
        #form.delete()


    else:
        #return json.dumps({'status': 'ok'})
        return render(request, 'daily_QA/'+str(gtr)+'.html', {'gtr': gtr, 'form': form}) #'datacheck': datacheck.count(), 'reload': last})

def submitted(form, current_user):
    

    

    # Check if the DailyTest instance already exists
    existing_hlavicka_instance = DailyTest.objects.filter(
        date_added=form.date_added,
        gantry=form.gantry
    ).first()

    # Create hlavicka_instance if it doesn't already exist
    if existing_hlavicka_instance is None:
        hlavicka_instance = DailyTest.objects.create(
            date_added= form.date_added,
            gantry=form.gantry,
            visionrt_check=form.visionrt_check,
            flatpanels_check=form.flatpanels_check,
            dynr=form.dynr,
            temperature=form.temperature,
            pressure=form.pressure,
            kfactor=form.kfactor,
            laserx=form.laserx,
            lasery=form.lasery,
            laserz=form.laserz,
            user=str(current_user)  # Assign the user to the instance
        )
        
    else:
        # Use the existing instance
        hlavicka_instance = existing_hlavicka_instance

    #Check dailyDraft length 
    total_non_none_count = 0
    total_non_none_count = sum(1 for field in form._meta.fields if getattr(form, field.name) is not None)
    print("Total count of non-None values across all fields in the dailydraft instance: {}".format(total_non_none_count)) #11 13 12 13

    total_non_none_count = sum(1 for field in hlavicka_instance._meta.fields if getattr(hlavicka_instance, field.name) is not None)
    print("Total count of non-None values across all fields in the daily instance: {}".format(total_non_none_count)) #30 32 37 43

    ### anebo toto nahradit disabled Submit btn dokud neni checkOfAllChecks
    

    #Check dailyDraft length 
    total_non_none_count = 0
    total_non_none_count = sum(1 for field in form._meta.fields if getattr(form, field.name) is not None)
    print("Total count of non-None values across all fields in the dailydraft instance: {}".format(total_non_none_count)) #11 13 12 13

    total_non_none_count = sum(1 for field in hlavicka_instance._meta.fields if getattr(hlavicka_instance, field.name) is not None)
    print("Total count of non-None values across all fields in the daily instance: {}".format(total_non_none_count)) #30 32 37 43

    ### anebo toto nahradit disabled Submit btn dokud neni checkOfAllChecks
    
    hlavicka_instance.save()

    for energy_var in [70,115,145,226]:
            
        existing_lynx_instance = DLynxMeasurement.objects.filter(
            Q(energy=energy_var) &
            Q(measurementid=hlavicka_instance)
        ).first()
        
        if existing_lynx_instance is None:

            lynx_instance = DLynxMeasurement(
            energy = energy_var,
            measurementid=hlavicka_instance,
            lynxid = form.lynxid,
            val99 = getattr(form,'lynx'+str(energy_var)+'_99'),
            val95 = getattr(form,'lynx'+str(energy_var)+'_95'),
            avg = getattr(form,'lynx'+str(energy_var)+'_avg'),
            max = getattr(form,'lynx'+str(energy_var)+'_max')
            )
        else:
        # Use the existing instance
            lynx_instance = existing_lynx_instance
        lynx_instance.save()

    for energy_var in [70,100,170,226]:

        existing_mlic_instance = DMlicMeasurement.objects.filter(
            Q(energy=energy_var) &
            Q(measurementid=hlavicka_instance)
        ).first()
        
        if existing_mlic_instance is None: # && mlic enabled
            mlic_instance = DMlicMeasurement(
            energy = energy_var,
            measurementid=hlavicka_instance,
            mlicid = form.mlicid,
            range = getattr(form,'mlic'+str(energy_var)+'_range')
            )

PTC_QA/daily_QA/templates/daily_QA/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    
  </head>
  <body>
    {% include 'daily_QA/navbar.html' %} 
    <br/>
    <div class="container"> 
    {% block content %} 
    {% endblock %}
    </div>
 

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


  </body>
</html>

PTC_QA/daily_QA/templates/daily_QA/daily_reload.html
{% extends "daily_QA/base.html" %}
  
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

{% block content %}

<h2>View the submitted daily tests</h2>

<label for="datepicker">Select Date:</label>
<input type="text" id="datepicker" placeholder="Select date">

<!-- Gantry selection dropdown -->
<label for="gantryDropdown">Select Gantry:</label>
<select id="gantryDropdown" onchange="selectGantry(this.value)">
  <option value="1">Gantry 1</option>
  <option value="2">Gantry 2</option>
  <option value="3">Gantry 3</option>
  <option value="4">Gantry 4</option>
</select>

<!-- Display the selected date and gantry -->
{% if selected_date %}
  <p>Selected Date: {{ selected_date }}</p>
{% endif %}
{% if selected_gantry %}
  <p>Selected Gantry: {{ selected_gantry }}</p>
{% endif %}

{% if filtered_rows %}
  <table border="1">
    <tr>
      <th>Index</th>
      <th>Gantry</th>
      <th>Date Added</th>
      <!-- Add more columns as needed -->
    </tr>
    {% for row in filtered_rows %}
      <tr>
        <td>{{ row.index }}</td>
        <td>{{ row.gantry }}</td>
        <td>{{ row.date_added }}</td>
        <!-- Add more columns as needed -->
      </tr>
    {% endfor %}
  </table>
{% endif %}

<!-- Initialize the date picker -->
<script>
  flatpickr("#datepicker", {
    dateFormat: "Y-m-d",
    onChange: function(selectedDates, dateStr, instance) {
      // Handle date selection, e.g., update URL or perform an action
      console.log(dateStr);
    }
  });

  function selectGantry(gantry) {
    // Handle gantry selection, e.g., update URL or perform an action
    console.log(gantry);
  }
</script>

{% endblock %}

PTC_QA/daily_QA/templates/daily_QA/entries_by_gtr.html
{% extends "daily_QA/base.html" %}

{% block content %}

<!-- entries_by_gtr.html -->
<!DOCTYPE html>
<html>

<body>
    <h1>Entries for TR {{ gtr }}</h1>
    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'daily_QA:entry_detail' entry.index %}">{{ entry.date_added|date:"Y-m-d" }} ({{ entry.index }})  </a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

{% endblock %}

PTC_QA/daily_QA/templates/daily_QA/entry_detail.html
{% extends "daily_QA/base.html" %}

{% block content %}

<!-- entry_detail.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Daily Test viewer</title>
    <style>       
        table {
            border-collapse: collapse;
            width: 69%;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .section-header {
            background-color: #68b9d4;
            color: #fff;
            padding: 10px;
            margin-top: 20px;
            width: 69%;
            font-size: 20px; /* Adjust the font size as needed */
            font-weight: bold; /* Make the font bold */
        }
    </style>
</head>
<body>
    <h1>Details for Entry {{ entry.index }} on {{ entry.date_added|date:"Y-m-d" }}</h1>
    
    <table>
        <tr>
            <th>Field</th>
            <th>Value</th>
        </tr>
        <tr>
            <td><strong>Gantry</strong></td>
            <td>{{ entry.gantry }}</td>
        </tr>
        <!-- Add other fields as needed -->
        <tr>
            <td><strong>VisionRT</strong></td>
            <td>
                {% if entry.visionrt_check == 1 %}
                    Pass
                {% elif entry.visionrt_check == None %}
                    None
                {% else %}
                    Fail
                {% endif %}
            </td>
        </tr>

        <tr>
            <td><strong>Flat Panels</strong></td>
            <td>
                {% if entry.flatpanels_check == 1 %}
                    Pass
                {% elif entry.flatpanels_check == None %}
                    None
                {% else %}
                    Fail
                {% endif %}
            </td>
        </tr>

        <tr>
            <td><strong>DynR</strong></td>
            <td>
                {% if entry.dynr_check == 1 %}
                    Pass
                {% elif entry.dynr_check == None %}
                    None
                {% else %}
                    Fail
                {% endif %}
            </td>
        </tr>

        <tr>
            <td><strong>Lasers XYZ</strong></td>
            <td>{{ entry.laserx }} {{ entry.lasery }} {{ entry.laserz }}</td>
        </tr>

        <tr>
            <td><strong>Temperature</strong></td>
            <td>{{ entry.temperature }}</td>
        </tr>

        <tr>
            <td><strong>Pressure</strong></td>
            <td>{{ entry.pressure }}</td>
        </tr>

        <tr>
            <td><strong>K factor</strong></td>
            <td>{{ entry.kfactor }}</td>
        </tr>

        <tr>
            <td><strong>User</strong></td>
            <td>{{ entry.user }}</td>
        </tr>
    </table>

    <div class="section-header">RANGE CHECK -  MLIC ID: {{ mlic.0.mlicid }}</div>
    
    <table>
        <tr>
            <th>Energy</th>
            <th>Range</th>
        </tr>
        {% for instance in mlic %}
            <tr>
                <td>{{ instance.energy }}</td>
                <td>{{ instance.range }}</td>
            </tr>
        {% endfor %}
    </table>

    <div class="section-header">FIELD CHECK -  LYNX ID: {{ lynx.0.lynxid }}</div>
    
    <table>
        <tr>
            <th>Energy</th>
            <th>Gamma &le; 1 [%]</th>
            <th>Gamma &le; 1,5 [%]</th>
            <th>Average</th>
            <th>Maximum</th>
        </tr>
        {% for instance in lynx %}
            <tr>
                <td>{{ instance.energy }}</td>
                <td>{{ instance.val95 }}</td>
                <td>{{ instance.val99 }}</td>
                <td>{{ instance.avg }}</td>
                <td>{{ instance.max }}</td>
            </tr>
        {% endfor %}
    </table>


    <div class="section-header">DOSE OUTPUT CHECK -  IC ID: {{ ic.0.ic_id }}</div>
    
    <table>
        <tr>
            <th>Energy</th>
            <th>Charge</th>
            <th>MU</th>
        </tr>
        {% for instance in ic %}
            <tr>
                <td>{{ instance.energy }}</td>
                <td>{{ instance.response_nc }}</td>
                <td>{{ instance.response_mu }}</td>

            </tr>
        {% endfor %}
    </table>

</body>





</html>

{% endblock %}

PTC_QA/daily_QA/templates/daily_QA/gtrselect.html
{% extends 'daily_QA/base.html' %}

{% block content %}

<li class='btn btn-primary'>
    <a class='btn btn-primary' href="{% url 'daily_QA:daily' '1' %}">FBTR1</a>
  </li>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha256-/ykJw/wDxMa0AQhHDYfuMEwVb4JHMx9h4jD4XvHqVzU=" crossorigin="anonymous" />
  
  <li class='btn btn-primary'>
    <a class='btn btn-primary' href="{% url 'daily_QA:daily' '2' %}">GTR2</a>
  </li>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha256-/ykJw/wDxMa0AQhHDYfuMEwVb4JHMx9h4jD4XvHqVzU=" crossorigin="anonymous" />

  <li class='btn btn-primary'>
    <a class='btn btn-primary' href="{% url 'daily_QA:daily' '3' %}">GTR3</a>
  </li>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha256-/ykJw/wDxMa0AQhHDYfuMEwVb4JHMx9h4jD4XvHqVzU=" crossorigin="anonymous" />

  <li class='btn btn-primary'>
    <a class='btn btn-primary' href="{% url 'daily_QA:daily' '4' %}">GTR4</a>
  </li>

  <br>
  <br>



{% endblock %}

PTC_QA/daily_QA/templates/daily_QA/home.html
{% extends 'daily_QA/base.html' %}

{% block content %}

<li class='btn btn-primary'>
    <a class='btn btn-primary' href="{% url 'daily_QA:gtrselect' %}">DailyQA</a>
  </li>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha256-/ykJw/wDxMa0AQhHDYfuMEwVb4JHMx9h4jD4XvHqVzU=" crossorigin="anonymous" />
  
  <li class='btn btn-primary'>
    <a class='btn btn-primary' href="{% url 'daily_QA:weekly' %}">WeeklyQA</a>
  </li>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha256-/ykJw/wDxMa0AQhHDYfuMEwVb4JHMx9h4jD4XvHqVzU=" crossorigin="anonymous" />

  <li class='btn btn-primary'>
    <a class='btn btn-primary' href="{% url 'daily_QA:monthly' %}">MonthlyQA</a>
  </li>

  <br>

  <br>



{% endblock %}

PTC_QA/daily_QA/templates/daily_QA/inlog.html
{% extends "daily_QA/base.html" %}

{% block content %}      

<!--Login--> 
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ loginform }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  </div>

{% endblock %}

PTC_QA/daily_QA/templates/daily_QA/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'daily_QA:home' %}">PTC Physics QA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        
      </ul> 
      <form class="form-inline my-2 my-lg-0">
        {% if user.is_authenticated %}
            <span class="navbar-text">
                You are logged in as {{ user.first_name }}  
            </span>

            <!-- Add space between text and button -->
            <div class="mr-2"></div>
            
            <a href="{% url 'daily_QA:logout' %}" class="btn btn-outline-danger my-2 my-sm-0">Logout</a>
        {% endif %}


      </form>
    </div>
  </nav>

PTC_QA/daily_QA/templates/daily_QA/submitted.html
{% extends 'daily_QA/base.html' %}

{% block content %}

{% load static %}

<h1>Good job, {{user.first_name}}! </h1>
<h2>You have submitted the daily test</h2>


{% endblock %}

PTC_QA/daily_QA/templates/daily_QA/weekly.html
{% load static %}

<input type="submit" id="submit" value="Submit">

<script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
<script type="text/javascript" src="{% static 'xd.js' %}"></script>